[package]
name = "engine-core"
version = "0.0.3"
edition = "2024"
build = "build.rs"

[[bin]]
name = "caqui"
path = "src/main.rs"

[dependencies]
rusqlite = { workspace = true }
deadpool-sqlite = { workspace = true }
deadpool = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
query-compiler = { path = "../query-compiler" }
schema-mapper = { path = "../schema-mapper" }
schema-parser = { path = "../schema-parser" }
api-layer = { path = "../api-layer" }
axum = { workspace = true }
clap = { workspace = true }
uuid = { version = "1.8", features = ["v7", "v4"] }

[dev-dependencies]
tempfile = { workspace = true }