[alias]
setup = "run --release --bin caqui -- init"
start = "run --release --bin caqui -- api start"
push = "run --release --bin caqui -- schema push"
migrate = "run --release --bin caqui -- schema migrate"
