[package]
name = "api-layer"
version = "0.0.6"
edition = "2024"

[dependencies]
schema-parser = { path = "../schema-parser" }
schema-mapper = { path = "../schema-mapper" }
query-compiler = { path = "../query-compiler" }
axum = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
deadpool-sqlite = { workspace = true }
deadpool = { workspace = true }
rusqlite = { workspace = true }
uuid = { version = "1.8", features = ["v7", "v4"] }
cuid = "1.3"

[dev-dependencies]
tower = { workspace = true }
